name: Spellcheck

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@0.60.0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
